### ISSUE TITLE
Complete Brand Pack

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#32]
**Objective**
Fill out the brand pack as completely and consistently as possible

**Description**

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Research
- [ ] Add
- [ ] Iterate

**Comment by malteserteresa** [comment]
Where did we get to with this btw?

**Comment by Cheukting** [comment]
How about we create a google share folder as our media pack? Putting the slide deck for lightning talks, with the branding docs that @jorgejativa created.

**Comment by malteserteresa** [comment]
Great idea! I've just made it, check slack for the link :)

**Comment by malteserteresa** [comment]
Completed
