### ISSUE TITLE
[WIP] Goals for OOT 2020 workshop

### ISSUE THREAD

**Issue by andra-pumnea** [opt-out-tools/start-here#35]
The question that we are trying to answer is: "where do we see Opt-Out at the end of the year?" and these are some of the points that came to our mind, both from an organisational and technical point of view. These goals will be further shaped and prioritised on the meetup in January 23rd. 

- first release Sept 2020
- dedicated, self-organised teams (data, activism, outreach)
- smooth onboarding for newbies
- become a legal entity
- have regular meetups, hackathons 
- setup crowdsourcing campaign
- user base = 100
- internal communication moderation tool for Mozilla (feasibility?)
- active contributing scene (at least 10 PR)

**Comment by malteserteresa** [comment]
After the meeting 23.01.20, it was clear that we need to revist goals for 2020. I suggest a workshop to develop and decide these goals

**Comment by malteserteresa** [comment]
Completed
