### ISSUE TITLE
Create Document Detailing Purpose for Funding Money

### ISSUE THREAD

**Issue by jorgejativa** [opt-out-tools/start-here#44]
We need to create a document creating detailing what we are going to do with the funds we obtain from crowdfunding. This is an important question we will get asked by multiple people and we need to respond to it accordingly and in a professional way. This is the first step towards setting up our crowdfunding page. Document where we are detailing goals for funding (asking the team): https://docs.google.com/document/d/1Py4TPT7ogkGrEn4AXd3jWSOLXr_lX4xYrgKLOobXVd8/edit

**Comment by malteserteresa** [comment]
Completed
