### ISSUE TITLE
Write questionnaire to help fill out content

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#49]
**Objective**
Write a short questionnaire that will help members of OOT generate content for the campaign

**Description**
The main issue with a marketing campaign is content. We can crowdsource this by writing a questionnaire that members of OOT fill out that we can then turn into content

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Draft questionnaire
- [ ] Critique at meetup on 17.02.20
- [ ] Send out to team members

**Comment by malteserteresa** [comment]
Questionnaire:
Why are you a part of Opt Out Tools
What problem do you think OOT solves and for whom?
Can you think of a culturally specific problem that OOT solves
How do you think some funding could help OOT

Please comment and we can rework it!

**Comment by sophielisawalker** [comment]
*What motivated you to become a part of Opt Out Tools?
*What are your hopes for OOT in the future? How would funding help?

"_What problem do you think OOT solves and for whom?
Can you think of a culturally specific problem that OOT solves_" - I think maybe these questions are too similar and could be rolled into one. Or do you see them as different?

**Comment by malteserteresa** [comment]
*What motivated you to become a part of Opt Out Tools?
*What are your hopes for OOT in the future? 
*How would funding help?
*Can you think of an example where OOT would have been useful? (Needs rewording, but I am trying to get personal or relatable stories into the campaign)
