### ISSUE TITLE
Build Presentation Packs

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/start-here#52]
**Objective**
Write a presenation and optional script for people to give lightening talks at meetups

**Description**

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Proof presentation
- [ ] Proof read script
- [ ] Make available to all

**Comment by malteserteresa** [comment]
Presentation pack:

Script:
[presentation_pack_script.pdf](https://github.com/opt-out-tools/start-here/files/4241414/presentation_pack_script.pdf)

Presentation:
[presentation_pack.pdf](https://github.com/opt-out-tools/start-here/files/4241416/presentation_pack.pdf)

@lucie-docs @teoguso 

Lucie if you could check the proof the presentation that would be great :) don't worry about the script

**Comment by lucie-docs** [comment]
@malteserteresa I had a quick look but it looks like it's an old version of the deck? There are things that would need changing, for example we can't submit reports from the website. Should I leave comments on the pdf and attach the version with my comments in this issue?

**Comment by malteserteresa** [comment]
Yeah sounds good! 

Also wrt submissions, it maybe someting we bring back, GDPR dependent, which I hope it communicated? 

Obviously website image will change once ours is up

**Comment by lucie-docs** [comment]
> Yeah sounds good!
> 
> Also wrt submissions, it maybe someting we bring back, GDPR dependent, which I hope it communicated?
> 
> Obviously website image will change once ours is up

Ok, I will take upload a version with my comments this weekend!

**Comment by malteserteresa** [comment]
Completed
